### PR TITLE
Doc lint and script reorg

### PR DESCRIPTION
**Pull request by ludoo**
Went a bit overboard, probably need more coding and less meetings ;)

### CODE REVIEW

**Comment by ludoo** [comment]
Example output

```
checking modules
  [✓] artifact-registry
  [✓] bigquery-dataset
  [✓] bigtable-instance
  [?] cloud-config-container
  [✓] cloud-function
  [✓] compute-mig
  [✓] compute-vm
  [✓] container-registry
  [✓] datafusion
  [✓] dns
  [✓] endpoints
  [✓] folder
  [✓] folders-unit
  [✓] gcs
  [✓] gke-cluster
  [✓] gke-nodepool
  [✓] iam-service-account
  [✓] kms
  [✓] logging-sinks
  [✓] net-address
  [✓] net-cloudnat
  [✓] net-ilb
  [✓] net-vpc
  [✓] net-vpc-firewall
  [✓] net-vpc-peering
  [✓] net-vpn-dynamic
  [✓] net-vpn-ha
  [✓] net-vpn-static
  [✓] organization
  [✓] project
  [✓] pubsub
  [✓] secret-manager
  [✓] service-directory
  [✓] source-repository
  [✓] vpc-sc
checking networking
  [✓] hub-and-spoke-peering
  [✓] hub-and-spoke-vpn
  [✓] ilb-next-hop
  [✓] onprem-google-access-dns
  [✓] shared-vpc-gke
checking foundations
  [✓] business-units
  [✓] environments
checking cloud-operations
  [✗] asset-inventory-feed-remediation
  [✗] dns-fine-grained-iam
  [✓] quota-monitoring
  [✓] scheduled-asset-inventory-export-bq
checking data-solutions
  [✗] cmek-via-centralized-kms
  [✓] gcs-to-bq-with-dataflow
errors were present
```

**Comment by ludoo** [comment]
Test failure is of course expected until we fix the stale READMEs. ;)

**Comment by ludoo** [comment]
Sent you a PR with a slight refactor :D

**Comment by juliocc** [comment]
LGTM

**Comment by juliocc** [comment]
nice output 👍

**Pull request merged**
