### PR TITLE
Fixed typo in pubsub/variables.tf.

### PR DESCRIPTION
**Pull request by noahdungey**
Fixed type in max_delivery_attempts variable name.

### CODE REVIEW

**Comment by ludoo** [comment]
Hey Noah, variables/outputs tables in the README are automatically built via the `tfdoc` script in the top-level `tools` folder. The lint step is filing because it finds a difference there. If you have trouble setting up the Python environment to run the script we can merge as-is and fix it ourselves later. And thanks for spotting this!

**Comment by juliocc** [comment]
> Hey Noah, variables/outputs tables in the README are automatically built via the `tfdoc` script in the top-level `tools` folder. The lint step is filing because it finds a difference there. If you have trouble setting up the Python environment to run the script we can merge as-is and fix it ourselves later. And thanks for spotting this!

on it ;)

**Review by juliocc — APPROVED** [review]

**Pull request merged**
