### PR TITLE
Added terraform.tfvars.sample

### PR DESCRIPTION
**Pull request by kumar-dhanagopal**
... to enable users to easily customize the configuration based on their requirements.

### CODE REVIEW

**Comment by juliocc** [comment]
I'm not really convinced of the value of having a sample tfvars file. Anyone somewhat familiar with terraform should be able to create one from variables.tf.

That being said, if we do want to include it, I would leave out all the variables with default values, specially if the value in the sample tfvars file is the same as the default.

**Comment by kumar-dhanagopal** [comment]
I agree that many users might be able to put together a tfvars file using variables.tf as a starting point. But I believe users will appreciate the convenience of a sample tfvars that they can quickly edit. 

I see your point about leaving out variables that have defaults already set in variables.tf. But again, when users start from a sample tfvars that includes all the declared variables, they won't need to hand-code any variables in the tfvars file, which is a convenience that some users might appreciate. I do recognize that this approach entails more maintenance overhead (for the code owners) to update 2 files when adding or changing variables.

**Comment by ludoo** [comment]
+1 on Julio's coments, I also don't think there should be unnecessary duplication. Code in this repo should adhere to Terraform best practices and do the sensible thing.

**Comment by kumar-dhanagopal** [comment]
Ok, Julio and Ludovico. The only variable that doesn't have a default in `variables.tf` is `project_id`. Providing a sample tfvars file with just one variable doesn't seem useful.

**Pull request closed without merging**
