### PR TITLE
Make examples in READMEs runnable and testable

### PR DESCRIPTION
**Pull request by juliocc**
This PR parses the READMEs for all the modules and runs them as tests. This ensures consistent examples that reflect the actual usage of the module.

### CODE REVIEW

**Comment by ludoo** [comment]
wow!

**Comment by juliocc** [comment]
61 new tests ;)

**Comment by ludoo** [comment]
We need a new trigger, the CB run times out ;)

**Comment by ludoo** [comment]
Can we add a trigger that filters to only kick in for changes in README files?

**Review by ludoo — APPROVED** [review]
this is actually great!

**Pull request merged**
