### PR TITLE
Remove location from local.prefix

### PR DESCRIPTION
**Pull request by yuryninog**
Let me know please if it could be work to close this issue: https://github.com/terraform-google-modules/cloud-foundation-fabric/issues/369.

### CODE REVIEW

**Review by ludoo — CHANGES_REQUESTED** [review]
Thanks a lot, I've been wanting to do this for ages but never actually got around to doing it. :)

I would maybe to away with `join` and use plain old string interpolation. Can you also make sure test pass?

**Comment by yuryninog** [comment]
Hi! @ludoo 

That is great! let me know please if this version could work please.

**Comment by yuryninog** [comment]
Hi @ludoo 

Great! Let me know please if this version could work please. Thank you! in advance.

**Review by ludoo — APPROVED** [review]
Thank you!

**Comment by juliocc** [comment]
@ludoo are we merging this?

**Comment by juliocc** [comment]
Thanks @yuryninog!

**Pull request merged**
