### PR TITLE
Added FW-Yaml module for distributed-firewall network example.

### PR DESCRIPTION
**Pull request by averbuks**
Tests are on the way.

### CODE REVIEW

**Comment by ludoo** [comment]
@juliocc we need to find a way to make example tests work for this ;)

**Comment by ludoo** [comment]
@averbuks one thing I'm a bit wary of with this is rule name clashes within the same project: what about using a format like `[vpc name]-[leaf directory name]-[name for the rule yaml block]`?

**Comment by averbuks** [comment]
> @averbuks one thing I'm a bit wary of with this is rule name clashes within the same project: what about using a format like `[vpc name]-[leaf directory name]-[file name]-[direction]-[name for the rule yaml block]`?
 
@ludoo good catch, I will incorporate vpc-name, I also like taking directory names, not sure about file name though.

**Comment by averbuks** [comment]
@ludoo I adjusted VPC name to the FW rule name, but decided to skip taking folder names for now. I would definitely do that if I'm a customer (so I can define a strict folder structure and naming), but let's keep it more generic for now. Someone can just define one yaml file in the same folder where main.tf resides and say `config_folder="./"`, so we have nothing to derive. 
WDYT?

**Review by ludoo — APPROVED** [review]
:+1:

**Pull request merged**
