### PR TITLE
Added CORS dynamic block for gcs : feature/cors for gcs

### PR DESCRIPTION
**Pull request by chinmaydorlikar**
- updated modules/gcs/main.tf : Added a dynamic cors block on line 65
- updated modules/gcs/variablles.tf : Added a variable for the cors block on line 103
- updated modules/gcs/README.md : Added a new row for the variable added

This is pertaining #231

### CODE REVIEW

**Comment by ludoo** [comment]
@chinmaydorlikar thanks for the PR! If it's not too much of a bother, could you run the `tfdoc` tool in the `tools` folder (Python requirements are listed there) against the module's directory, so that the README is updated? The other failing test is unrelated.

If it's a hassle just tell me and I'll merge and run it after. Thanks!

**Review by ludoo — APPROVED** [review]
README needs to be updated via `tfdoc`

**Comment by chinmaydorlikar** [comment]
Ran tfdoc for /module/gcs/README.md.
The tfdoc tool is amazing btw! This is the first time I am using tfdoc.

**Comment by ludoo** [comment]
> Ran tfdoc for /module/gcs/README.md.
> The tfdoc tool is amazing btw! This is the first time I am using tfdoc.

Ahah thanks, it was a bet and took several nights of work. :) I should probably migrate it to use the `python-hcl2` library!

**Pull request merged**
