### PR TITLE
Add support for lifecycle_rule in gcs module

### PR DESCRIPTION
**Pull request by IuryAlves**
This PR adds support for [lifecycle_rule](https://registry.terraform.io/providers/hashicorp/google/latest/docs/resources/storage_bucket#example-usage---life-cycle-settings-for-storage-bucket-objects)  in GCS module.

### CODE REVIEW

**Comment by ludoo** [comment]
Iury, can you run `tools/tfdoc.py` against the `modules/gcs` folder?

**Comment by IuryAlves** [comment]
> tools/tfdoc.py

I got no output from `tools/tfdoc.py modules/gcs`

@ludoo

**Comment by ludoo** [comment]
> I got no output from `tools/tfdoc.py modules/gcs`

Yep it directly modifies the module's README by default.

**Comment by ludoo** [comment]
Hmm, let e have a look at what's failing. We also need to fix the module's test.

**Comment by ludoo** [comment]
Let me merge this to a local branch and I can then fix it, it will be much quicker. :) I'll cc you in the new PR ofc.

**Pull request merged**
