### PR TITLE
[#223] Remove unused IAM policies from shared-vpc-gke example

### PR DESCRIPTION
**Pull request by LucaPrete**

### CODE REVIEW

**Comment by LucaPrete** [comment]
@juliocc @ludoo I don't find a sense to those IAM bindings, but please let me know if I'm missing something :)

**Comment by juliocc** [comment]
This is my understanding:
- roles/container.developer: required from the bastion to deploy to/query the cluster
- roles/logging.logWriter, roles/monitoring.metricWriter, roles/stackdriver.resourceMetadata.writer: required by the nodes to send metrics/logs to Cloud Ops

@ludoo can you confirm

**Comment by ludoo** [comment]
> * roles/container.developer: required from the bastion to deploy to/query the cluster

yes

> * roles/logging.logWriter, roles/monitoring.metricWriter, roles/stackdriver.resourceMetadata.writer: required by the nodes to send metrics/logs to Cloud Ops

yes

**Comment by ludoo** [comment]
But Luca's point is that those are just cloned from the gke service project, and rference the gke node SA, in the gce project so they can be safely removed.

**Comment by LucaPrete** [comment]
Yes, indeed @juliocc I see the same roles configured in the GKE project, where insteadI think they make sense.
I also brought up a cluster without those roles and I see everything working correctly.

**Pull request merged**
